default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: <%= Rails.application.credentials.mysql[:local_password] %>
  database: mmss-mysql_development

test:
  <<: *default
  username: root
  password: <%= Rails.application.credentials.mysql[:local_password] %>
  database: mmss-mysql_test

production:
  <<: *default
  username: <%= Rails.application.credentials.PRODUCTION_DB_USERNAME %>
  password: <%= Rails.application.credentials.PRODUCTION_DB_PASSWORD %>
  database: mmss-mysql_production
