default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['LOCAL_MYSQL_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: mmss-mysql_development

test:
  <<: *default
  database: mmss-mysql_test

production:
  <<: *default
  database: mmssprod
  username: <%= Rails.application.credentials.mysql[:prod_user] %>
  password: <%= Rails.application.credentials.mysql[:prod_password] %>
  host: <%= Rails.application.credentials.mysql[:prod_servername] %>
  sslca: <%= Rails.application.credentials.mysql[:prod_sslca] %>
